### PR TITLE
Pins are now displayed dynamically

### PR DESCRIPTION
**Pull request by joowoonk**
## Description ##

Clearly documents the reason for the pull request and what has changed.
- [ ] This is a bugfix.
- [ ] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [x] Have you added two reviewers to this pull request?
- [ ] Is this a work in process?
- [ ] Is this ready to be reviewed?

### CODE REVIEW

**Comment by joowoonk** [comment]
[Map Display](https://trello.com/c/P6nJizDb/21-map-display)

**Review by devjaymoe — APPROVED** [review]
Worked live with changes made to files.

**Review by jessicagertig — CHANGES_REQUESTED** [review]
Nice job getting the pin working and displaying the dummy data.  I can see there is some commented out code.  Is any of it code you plan to use later when we start receiving data from the backend?  If so please add that as a comment.  Otherwise go ahead and remove the commented out code and push a commit and you are good to go!!!  On fire!

**Comment by joowoonk** [comment]
[Map Display](https://trello.com/c/P6nJizDb/21-map-display)

**Comment by joowoonk** [comment]
[Map Display](https://trello.com/c/P6nJizDb/21-map-display)

**Comment by joowoonk** [comment]
pins are now displayed dynamically, data can have more than one object, working and filtering atm and styling of words are done but as panel no t sure yet, will def work on those later on

**Review by jessicagertig — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
