### PR TITLE
File refactor

### PR DESCRIPTION
**Pull request by devjaymoe**
## Description ##

Clearly documents the reason for the pull request and what has changed.
- [ ] This is a bugfix.
- [ ] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [x] Have you added two reviewers to this pull request?
- [ ] Is this a work in process?
- [x] Is this ready to be reviewed?

### CODE REVIEW

**Review by joowoonk — APPROVED** [review]

**Comment by devjaymoe** [comment]
[Refactor File Structure](https://trello.com/c/0eqgaS3e/25-refactor-file-structure)

**Review by RobertMisch — APPROVED** [review]
Good work resolving the merge conflicts from earlier and cleaning up the structure.

**Review by jessicagertig — APPROVED** [review]
As we all discussed, the file structure on the frontend needed multiple files removed from the template starter and also in the index.js containing the routes since for the time being we are not requiring authentication in order to access our homepage/visualization.

**Comment by jessicagertig** [comment]
Need to go alter code climate file as needed due to the deletions.

**Pull request merged**
